# Generated by Django 3.0.6 on 2020-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('year', models.IntegerField(default=2015, verbose_name='Год')),
                ('author', models.CharField(blank=True, max_length=255, null=True, verbose_name='Автор')),
            ],
        ),
    ]
